# Generated by Django 4.0.1 on 2022-02-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_egn_alter_employee_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='egn',
        ),
    ]
