# Generated by Django 4.0.1 on 2022-02-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_remove_user_id_alter_user_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('company', '-first_name')},
        ),
    ]
